apiVersion: v1
kind: Secret
metadata:
  name: miracle6-k8s
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:kramarov666/miracle6-k8s.git
  sshPrivateKey: |
    SSH_KEY_PLACEHOLDER