name: terraform

concurrency:
  group: terraform-prod
  cancel-in-progress: true

on: workflow_dispatch

env:
  TF_VERSION: 1.15
  TF_PLUGIN_CACHE_DIR: /home/runner/work/terraform-micro/terraform-micro/eks/.terraform.d/plugin-cache

permissions:
  id-token: write
  contents: read

jobs:

  terraform-plan:
    environment: preprod
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./eks
  
    steps:

    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:
        role-to-assume: ${{ vars.TF_ROLE_ARN_READONLY }}
        role-session-name: tf-session
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
    
    - run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

    - name: Cache Terraform
      uses: actions/cache@v6
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: terraform-${{ runner.os }}-${{ hashFiles('.terraform.lock.hcl') }}
        restore-keys: |
          terraform-${{ runner.os }}-
    
    - name: Terraform Init
      id: init
      run: terraform init -input=false --lockfile=readonly

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false --out=tf_output.tfplan
    
    - name: Upload file
      uses: actions/upload-artifact@v6
      with:
        name: tfplan
        path: tf_output.tfplan
        retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    environment: prod
    needs: terraform-plan

    defaults:
      run:
        shell: bash
        working-directory: ./eks
  
    steps:

    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:
        role-to-assume: ${{ vars.TF_ROLE_ARN_ADMIN }}
        role-session-name: tf-sesssion
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Download file
      uses: actions/download-artifact@v4
      with:
        name: tfplan

    - run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

    - name: Cache Terraform
      uses: actions/cache@v6
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: terraform-${{ runner.os }}-${{ hashFiles('.terraform.lock.hcl') }}
        restore-keys: |
            terraform-${{ runner.os }}-
    
    - name: Terraform Init
      id: init
      run: terraform init -input=false -lockfile=readonly

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color tf_output.tfplan